# Generated by Django 5.0.7 on 2024-12-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_expense_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
